GET http://localhost:8000/api/cards
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzI0OTJkN2QzOWZmYjg3NTBjOWY1NjAiLCJiaXoiOmZhbHNlLCJpYXQiOjE2NjMzNDEyNzF9.xmcaq2YhNeqDGO9l58XVU_k_EIY228nbRQPW_5OmrVo

###

GET http://localhost:8000/api/myCards
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzI0OTJkN2QzOWZmYjg3NTBjOWY1NjAiLCJiaXoiOmZhbHNlLCJpYXQiOjE2NjMzNDEyNzF9.xmcaq2YhNeqDGO9l58XVU_k_EIY228nbRQPW_5OmrVo

###
POST http://localhost:8000/api/cards
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzI0Y2JiYjA5YjRkY2E5NDFkMThhNWQiLCJiaXoiOmZhbHNlLCJpYXQiOjE2NjMzNTU4MzV9.SLFeRbNkwmkSaSUJiLJUwGQwSuBFpJ2nKNF-XzK7Pi0

{
"bizName": "my Biz 6",
"bizDescription": "bla bla",
"bizAddress": "12 strii Tel Aviv",
"bizPhone": "08-9131900",
"bizImage": "https://www.averbuch.co.il/images/ul240756/a4cf6d6e7e23c60bf21a555099e314cc.png"
}

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "israel@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "avi",
    "email": "avi@gmail.com",
    "password": "12345678"
}